### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by Vulchare** [exercism/exercism.io#2333]
I'm not sure where to go from here.
Ive installed JDK and Gradle. Yet when I try to run gradle test it shows the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type DefaultClassLoaderRegistry using GlobalScopeSer
vices.createClassLoaderRegistry().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

With --debug

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type DefaultClassLoaderRegistry using GlobalScopeSer
vices.createClassLoaderRegistry().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

With --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type DefaultClassLoaderRegistry using GlobalScopeSer
vices.createClassLoaderRegistry().

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.internal.service.ServiceCreationException: Could not create service o
f type DefaultClassLoaderRegistry using GlobalScopeServices.createClassLoaderReg
istry().
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodServi
ce.invokeMethod(DefaultServiceRegistry.java:643)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.cre
ate(DefaultServiceRegistry.java:597)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvi
der.getInstance(DefaultServiceRegistry.java:439)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.g
et(DefaultServiceRegistry.java:479)
        at org.gradle.internal.service.DefaultServiceRegistry.findConfigureMetho
d(DefaultServiceRegistry.java:145)
        at org.gradle.internal.service.DefaultServiceRegistry.findProviderMethod
s(DefaultServiceRegistry.java:119)
        at org.gradle.internal.service.DefaultServiceRegistry.addProvider(Defaul
tServiceRegistry.java:227)
        at org.gradle.internal.service.ServiceRegistryBuilder.build(ServiceRegis
tryBuilder.java:52)
        at org.gradle.launcher.cli.BuildActionsFactory.runBuildInProcess(BuildAc
tionsFactory.java:159)
        at org.gradle.launcher.cli.BuildActionsFactory.createAction(BuildActions
Factory.java:133)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
createAction(CommandLineActionFactory.java:242)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:232)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
trap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
ava:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: java.lang.IllegalArgumentException: Cannot find JAR 'bcprov-jdk15on-1
.51.jar' required by module 'gradle-dependency-management' using classpath or di
stribution directory 'C:\gradle-2.3-all\gradle-2.3'
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.findDependenc
yJar(DefaultModuleRegistry.java:256)
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.module(Defaul
tModuleRegistry.java:143)
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.loadModule(De
faultModuleRegistry.java:120)
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.getModule(Def
aultModuleRegistry.java:108)
        at org.gradle.api.internal.DynamicModulesClassPathProvider.findClassPath
(DynamicModulesClassPathProvider.java:41)
        at org.gradle.api.internal.DefaultClassPathRegistry.getClassPath(Default
ClassPathRegistry.java:34)
        at org.gradle.initialization.DefaultClassLoaderRegistry.<init>(DefaultCl
assLoaderRegistry.java:38)
        at org.gradle.internal.service.scopes.GlobalScopeServices.createClassLoa
derRegistry(GlobalScopeServices.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.internal.service.DefaultServiceRegistry.invoke(DefaultServ
iceRegistry.java:328)
        at org.gradle.internal.service.DefaultServiceRegistry.access$1200(Defaul
tServiceRegistry.java:58)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodServi
ce.invokeMethod(DefaultServiceRegistry.java:641)
        ... 27 more

**Comment by kytrinyx** [comment]
@Vulchare did you get this figured out? If so, is there something that we could have done in the readme or documentation to help you get it solved more quickly?

**Comment by Vulchare** [comment]
Hi,

Yes, I've tried a full reinstall and it worked. I imagined closing the
issue would consider it solved.

The readme file is fine :)

Thanks for responding so quickly
Op 8 apr. 2015 03:57 schreef "Katrina Owen" <notifications@github.com>:

**Comment by kytrinyx** [comment]
Cool -- yeah sometimes people give up and close the issue before we can help figure things out, and every once in a while their confusion is the key to making something better on our end.

Thanks :)
