### ISSUE TITLE
Error parsing API response

### ISSUE THREAD

**Issue by Wuppert** [exercism/exercism.io#3506]
Hi

just after
exercism fetch java
i get 
Error parsing API response - invalid character 'i' looking for beginning of value

The error is:

```
>exercism fetch java
2017/05/17 13:10:08 error parsing API response - invalid character 'i' looking for beginning of value
```

The debug output is:

```
>exercism debug

**** Debug Information ****
Exercism CLI Version: 2.4.0
Exercism CLI Latest Release: 2.4.0
OS/Architecture: windows/386
Build OS/Architecture windows/386
Home Dir: C:\Users\e0602010
Config File: C:\Users\e0602010\.exercism.json
API Key: 7979*************************d7d
Exercises Directory: C:\Users\e0602010\my-exercism-exercises
Testing API endpoints reachability
        * GitHub API: https://api.github.com/ [connected] 137.9862ms
        * API: http://exercism.io [connected] 389.961ms
        * XAPI: http://x.exercism.io [connected] 474.9525ms

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
```

**Comment by kytrinyx** [comment]
In the future, please paste your errors and output directly into the issue using GitHub markdown's "fenceposts" (See https://guides.github.com/features/mastering-markdown/ for details).

I've edited your issue to remove the link to the PDF, which contained your exercism API key, and paste in the plain text of the output that we need to see.

I'd recommend changing your API key by going to http://exercism.io/account/key and clicking "reset key". You'll need to reconfigure the key in the CLI using the command displayed on that page.

I'm looking into this issue now.

**Comment by kytrinyx** [comment]
@Wuppert Would you please run the command:

```
exercism --verbose fetch java
```

And then paste the output here? Remember to redact your API key from the output.

**Comment by Wuppert** [comment]
@kytrinyx
Katrina could you explain please term "fenceposts".

key chenged
exercism --verbose fetch java
output:
```
>Microsoft Windows [Version 6.1.7601]
(c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.

C:\Users\e0602010>exercism --verbose fetch java
verbose logging enabled
Request GET http://x.exercism.io/v2/exercises/java?key=8675cfd04f6e424aab2429418b0bd5bd
Response StatusCode=200
Response Body
{"problems":[{"id":"java/hello-world","track_id":"java","language":"java","slug":"hello-world","name":"Hello W
orld","files":{"GETTING_STARTED.md":"----\n# Quick Start Guide\n\nThis guide picks-up where [Running the Tests
 (in Java)](http://exercism.io/languages/java/tests)\nleft off.  If you haven't reviewed those instructions, d
o so now.\n\nNeed more information?  A **step-by-step tutorial** is available in this directory at TUTORIAL.md
 or you can read \nthe [HTML version](https://github.com/exercism/xjava/blob/master/exercises/hello-world/TUTO
RIAL.md).\n\nThe following instructions work equally well on Windows, Mac OS X and Linux.\n\n## Solve \"Hello
World\"\n\nTry writing a solution that passes one test at a time, running Gradle each time:\n\n\n```\n$ gradle
 test\n```\n\n## Iterate through the tests\n\nAfter your first test passes, remove the `@Ignore` from the next
 test, and iterate on your solution,\ntesting after each change.\n\n## All the tests pass?  Submit your soluti
on!\n\nWith a working solution that we've reviewed, we're ready to submit it to\nexercism.io.\n\n```\n$ exerci
sm submit src/main/java/HelloWorld.java\n```\n\n## Next Steps\n\nFrom here, there are a number of paths you ca
n take.\n\n1. Move on to the next exercise\n2. Review (and comment on) others' submissions to this exercise\n3
. Submit another iteration\n4. Contribute to Exercism\n\n\nWe sincerely hope you learn and enjoy being part of
 this community.  If at any time you need assistance\ndo not hesitate to ask for help:\n\nhttp://exercism.io/l
anguages/java/help\n\nCheers!\n","TUTORIAL.md":"NOTE: You can also view the HTML version of this file here:\nh
ttps://github.com/exercism/xjava/blob/master/exercises/hello-world/TUTORIAL.md\n\n* [Solving \"Hello, World!\"
](#solving-hello-world)\n * [Reading Gradle output](#reading-gradle-output)\n * [Fixing the first failing test
](#fixing-the-first-failing-test)\n * [Enabling and fixing the second test](#enabling-and-fixing-the-second-te
st)\n * [Enabling the last test](#enabling-the-last-test)\n * [Refactoring](#refactoring)\n* [Submitting your
first iteration](#submitting-your-first-iteration)\n* [Next Steps](#next-steps)\n * [Review (and comment on) o
thers' submissions to this exercise](#review-and-comment-on-others-submissions-to-this-exercise)\n * [Extend a
n exercise](#extend-an-exercise)\n\n----\n\n# Solving \"Hello, World!\"\n\nWelcome to the first exercise on th
e Java track!\n\nThis is a step-by-step guide to solving this exercise.\n\nEach exercise comes with a set of t
ests.  The first pass through the\nexercise is about getting all of the tests to pass, one at a time.\n\nIf yo
u have not installed the Java Development Kit and Gradle, you must do\nso now.  For help with this, see: http:
//exercism.io/languages/java/installing\n\n----\n\nThis guide picks-up where [Running the Tests (in Java)](htt
p://exercism.io/languages/java/tests)\nleft off.  If you haven't reviewed those instructions, do so now.\n\nTh
e following instructions work equally well on Windows, Mac OS X and Linux.\n\n## Reading Gradle output\n\nUse
Gradle to run the tests:\n\n```\n$ gradle test\n```\n\nThis command does a lot and displays a bunch of stuff.
 Let's break it down...\n\n```\n:compileJava\n:processResources UP-TO-DATE\n:classes\n```\n\nEach line that be
gins with a colon (like `:compileJava`) is Gradle telling\nus that it's starting that task.  The first three t
asks are about compiling\nthe source code of our *solution*. We've done you a favor and included just\nenough
code for the solution that it compiles.\n\nWhen a task is successful, it generally does not output anything.
This is\nwhy `:compileJava` and `:classes` do not produce any additional output.\n`:processResources` reports
that it had nothing to do.\n\nSo far, so good...\n\nThe next three tasks are about compiling source code of th
e *tests*.\n\n```\n:compileTestJava\n:processTestResources UP-TO-DATE\n:testClasses\n```\n\n... with both sets
 of source code successfully compiled, Gradle turns to\nrunning the task you asked it to: executing the tests
against the solution.\n\n```\n:test\n\nHelloWorldTest > helloNoName FAILED\n    java.lang.AssertionError: expe
cted:<Hello, World!> but was:<null>\n        at org.junit.Assert.fail(Assert.java:93)\n        at org.junit.As
sert.failNotEquals(Assert.java:647)\n        at org.junit.Assert.assertEquals(Assert.java:128)\n        at org
.junit.Assert.assertEquals(Assert.java:147)\n        at HelloWorldTest.helloNoName(HelloWorldTest.java:10)\n\n
HelloWorldTest > helloSampleName SKIPPED\n\nHelloWorldTest > helloAnotherSampleName SKIPPED\n\n3 tests complet
ed, 1 failed, 2 skipped\n:test FAILED\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nExecu
tion failed for task ':test'.\n> There were failing tests. See the report at: file:///Users/jtigger/projects/e
xercism/xjava/build/exercism/java/hello-world/build/reports/tests/index.html\n\n* Try:\nRun with --stacktrace
option to get the stack trace. Run with --info or --debug option to get more log output.\n\nBUILD FAILED\n\nTo
tal time: 6.716 secs\n```\n\nSeeing the word \"fail\" TEN TIMES might give you the impression you've done\nsom
ething horribly wrong.  You haven't.  It's a whole lot of noise over\na single test not passing.\n\nLet's focu
s in on the important bits:\n\n```\nHelloWorldTest > helloNoName FAILED\n    java.lang.AssertionError: expecte
d:<Hello, World!> but was:<null>\n```\n\n...is read: \"Within the test class named `HelloWorldTest`, the test
method\n`helloNoName` did not pass because the solution did not satisfy an\nassertion.  Apparently, we expecte
d to see the string 'Hello, World!' but\nthe value `null` was returned instead.\n\nThe last line of the stack
trace tells us exactly where this unsatisfied\nassertion lives:\n\n```\n        at HelloWorldTest.helloNoName(
HelloWorldTest.java:10)\n```\n\nLooks like the crime was discovered on line 10 in the test file.\n\nKnowing th
ese two facts,\n\n1. the return value was not what was expected, and\n2. the failure was on line 10 of the tes
t,\n \nwe can turn this failure into success.\n\n\n\n## Fixing the first failing test\n\nIn your favorite text
 editor, open `src/test/java/HelloWorldTest.java`\nand go to line 10.\n\n```java\nassertEquals(\"Hello, World!
\", HelloWorld.hello(\"\"));\n```\n\nThe test is expecting that `hello()`, when given an empty string (`\"\"`)
,\nreturns \"Hello, World!\".  Instead, `hello()` is returning `null`.\nLet's fix that.\n\nOpen `src/main/java
/HelloWorld.java`.\n\n```java\npublic class HelloWorld {\n  public static String hello(String name) {\n    ret
urn null;\n  }\n}\n```\n\nLet's change that to return the expected string:\n\n```java\npublic class HelloWorld
 {\n  public static String hello(String name) {\n    return \"Hello, World!\";\n  }\n}\n```\n\nSave the file a
nd run the tests again:\n\n```\n$ gradle test\n:compileJava\n:processResources UP-TO-DATE\n:classes\n:compileT
estJava\n:processTestResources UP-TO-DATE\n:testClasses\n:test\n\nHelloWorldTest > helloAnotherSampleName SKIP
PED\n\nHelloWorldTest > helloNoName PASSED\n\nHelloWorldTest > helloSampleName SKIPPED\n\nBUILD SUCCESSFUL\n\n
Total time: 4.523 secs\n```\n\n\"BUILD SUCCESSFUL\"!  Woohoo! :)  You can see that `helloNoName()` test is\nno
w passing.\n\nWith one win under our belt, we can turn our focus to some other messages\nthat we've been ignor
ing: the lines ending in \"`SKIPPED`\".\n\nEach test suite contains a series of tests, all of which have been
marked\nto be skipped/ignored except the first one.  We did this to help you focus\non getting one test runnin
g at a time.\n\nLet's tackle the next test...\n\n\n\n## Enabling and fixing the second test\n\nRight now, that
 second test is being skipped/ignored.  Let's enable it.\n\n(Re)open `src/test/java/HelloWorldTest.java` and f
ind the second test:\n\n```java\n...\n@Test\n@Ignore\npublic void helloSampleName() {\n  assertEquals(\"Hello,
 Alice!\", HelloWorld.hello(\"Alice\"));\n}\n...\n```\n\nWhen the JUnit test runner sees that `@Ignore` annota
tion on the test\nmethod, it knows to skip over that test.  Remove that line:\n\n```java\n...\n@Test\npublic v
oid helloSampleName() {\n  assertEquals(\"Hello, Alice!\", HelloWorld.hello(\"Alice\"));\n}\n...\n```\n\nNow,
when you run the tests, both tests run:\n\n```sh\n$ gradle test\n...\n:test\n\nHelloWorldTest > helloNoName PA
SSED\n\nHelloWorldTest > helloSampleName FAILED\n    org.junit.ComparisonFailure: expected:<Hello, [Alice]!> b
ut was:<Hello, [World]!>\n        at org.junit.Assert.assertEquals(Assert.java:125)\n        at org.junit.Asse
rt.assertEquals(Assert.java:147)\n        at HelloWorldTest.helloSampleName(HelloWorldTest.java:16)\n\nHelloWo
rldTest > helloAnotherSampleName SKIPPED\n\n3 tests completed, 1 failed, 1 skipped\n...\n```\n\nThe first test
, `helloNoName()` continues to pass.  We see that\n`helloSampleName` -- the test we just un-`@Ignore`'d -- is
now running and\nfailing.  Yay, failing test!  In fact, the \"failure\" message is just\ndescribing the differ
ence between what the program does now and what it\nshould do for us to call it \"done.\"\n\nRight now, we've
hardcoded the greeting.  Enabling this second test has\nunleashed a new expectation: that our program incorpor
ate a name given\ninto that greeting.  When given the name \"`Alice`\", that's who should be\ngreeted instead
of \"`World`\".\n\n(Re)open `src/main/java/HelloWorld.java`.\n\n```java\npublic class HelloWorld {\n  public s
tatic String hello(String name) {\n    return \"Hello, World!\";\n  }\n}\n```\n\nWhile `hello()` does accept a
 reference to a string named `name`, it is not\nusing it in the output.  Let's change that:\n\n\n```java\npubl
ic class HelloWorld {\n  public static String hello(String name) {\n    return \"Hello, \" + name + \"!\";\n
}\n}\n```\n\n... and rerun the tests ...\n\n```\n$ gradle test\n:test\n\nHelloWorldTest > helloAnotherSampleNa
me SKIPPED\n\nHelloWorldTest > helloNoName FAILED\n    org.junit.ComparisonFailure: expected:<Hello, [World]!>
 but was:<Hello, []!>\n        at org.junit.Assert.assertEquals(Assert.java:125)\n        at org.junit.Assert.
assertEquals(Assert.java:147)\n        at HelloWorldTest.helloNoName(HelloWorldTest.java:10)\n\nHelloWorldTest
 > helloSampleName PASSED\n\n3 tests completed, 1 failed, 1 skipped\n```\n\nWait... didn't we just fix the tes
t?  Why is it failing?  Take a closer look...\n\nIn fact, `helloSampleName()` *is* passing.  It's just that at
 the same time,\nwe just inadvertently broke that first test: `helloNoName()`.\n\nThis is one tiny example of
the benefit of maintaining a test suite: if we\nuse them to drive out our code, the second we break the progra
m the tests\nsay so.  Since we saw them passing just *before* our latest change,\nwhatever we *just* did most
likely cause that regression.\n\nOur latest change was making the greeting dependent on the name given. Our\nf
irst test expects that if either a blank string or null are given as the\nname, then \"`World`\" should be sub
stituted in.  Let's implement that.\n\n`src/main/java/HelloWorld.java`:\n```java\npublic class HelloWorld {\n
 public static String hello(String name) {\n    if(name == null || \"\".equals(name)) {\n      name = \"World\
";\n    }\n    return \"Hello, \" + name + \"!\";\n  }\n}\n```\n\n... and re-run the tests ...\n\n```\n$ gradl
e test\n...\n:test\n\nHelloWorldTest > helloNoName PASSED\n\nHelloWorldTest > helloSampleName PASSED\n\nHelloW
orldTest > helloAnotherSampleName SKIPPED\n\nBUILD SUCCESSFUL\n\nTotal time: 4.804 secs\n```\n\nExcellent!  We
're now (at least) two-thirds the way done.  Just one more\ntest to go...\n\n\n\n## Enabling the last test\n\n
(Re)open `src/test/java/HelloWorldTest.java` and find the last test:\n\n```java\n...\n@Test\n@Ignore\npublic v
oid helloAnotherSampleName() {\n    assertEquals(\"Hello, Bob!\", HelloWorld.hello(\"Bob\"));\n}\n...\n```\n\n
... and remove it's `@Ignore` to enable it ...\n\n```java\n...\n@Test\npublic void helloAnotherSampleName() {\
n    assertEquals(\"Hello, Bob!\", HelloWorld.hello(\"Bob\"));\n}\n...\n```\n\n... and re-run the tests ...\n\
n```\n$ gradle test\n:compileJava UP-TO-DATE\n:processResources UP-TO-DATE\n:classes UP-TO-DATE\n:compileTestJ
ava\n:processTestResources UP-TO-DATE\n:testClasses\n:test\n\nHelloWorldTest > helloNoName PASSED\n\nHelloWorl
dTest > helloSampleName PASSED\n\nHelloWorldTest > helloAnotherSampleName PASSED\n\nBUILD SUCCESSFUL\n\nTotal
time: 6.953 secs\n```\n\nOh, hello!  Turns out, the solution we put into place didn't just apply for\n\"`Alice
`\" but \"`Bob`\" equally well.  In this case, the test succeeded with\nno additional code on our part.\n\n\n\
n## Refactoring\n\nNow that you've got all the tests passing, you might consider whether\nthe code is in the m
ost readable/maintainable/efficient shape.  What makes\nfor \"good\" design of software is a big topic.  The p
ursuit of it underlies\nmuch of what makes up the more valuable conversations on Exercism.\n\nFor now, let's j
ust take a quick review of our solution and see if there's\nany part of it we'd like to refactor.  Refactoring
 is changing the way\na bit of code reads without changing what it does.\n\nRight now, the details of detectin
g whether the caller of `hello()` has\ngiven a name or not (i.e. `name` is either `null` or an empty string) i
s\nsitting right next to the core responsibility of the method: to produce a\npersonalized greeting.\n\n```jav
a\npublic class HelloWorld {\n  public static String hello(String name) {\n    if(name == null || \"\".equals(
name)) {\n      name = \"World\";\n    }\n    return \"Hello, \" + name + \"!\";\n  }\n}\n```\n\nHow would thi
ngs read if we extracted those details into a separate method\nand at the same time, replaced the `if` with a
ternary expression?\n\n```java\npublic class HelloWorld {\n\n  public static String hello(String name) {\n
String whom = isBlank(name) ? \"World\" : name;\n    return \"Hello, \" + whom + \"!\";\n  }\n\n  private stat
ic boolean isBlank(String string) {\n    return string == null || \"\".equals(string);\n  }\n}\n```\n\nBy extr
acting that logic into the `isBlank()` method, we've added a little\nabstraction to our program -- it's not as
 literal as it was before.  Yet,\nit allows us to defer *needing* to understand *how* \"blankness\" is\ndetect
ed.  If we can assume that `isBlank()` just works, we don't have to\ndownshift in our head to those details.
Instead, we can remain at the same\nlevel of thinking: to whom are we greeting?\n\nThe ternary operator allowe
d us to express that choice in a more compact\nform.  Less to read without losing the intent.\n\nFinally, we i
ntroduced another variable: `whom`.  Doing so gives a name to\nthe output of the ternary expression.  We certa
inly could have continued\nto reuse `name`, but by introducing a second `String` to hold the\ncalculated value
 this keeps crisp the two ideas: `name` is what's given\nand `whom` is what's been determined.\n\nWe made a bu
nch of changes, let's make sure we didn't break the program!\n\n```\n$ gradle test\n...\nHelloWorldTest > hell
oNoName PASSED\n\nHelloWorldTest > helloSampleName PASSED\n\nHelloWorldTest > helloAnotherSampleName PASSED\n.
..\n```\n\nThis illustrates another benefit of writing tests: you can make significant\nchanges to the structu
re of the program and very quickly restore your\nconfidence that the program still works.  These tests are a f
ar cry from a\n\"proof\" of correctness, but well-written tests do a much better job of\n(very quickly) giving
 us evidence that it is.  Without them, we manually\nrun the program with different inputs and/or inspecting t
he code\nline-by-line -- time-consuming and error prone.\n\n\n\n# Submitting your first iteration\n\nWith a wo
rking solution that we've reviewed, we're ready to submit it to\nexercism.io.\n\n```\n$ exercism submit src/ma
in/java/HelloWorld.java\n```\n\n\n\n# Next Steps\n\nFrom here, there are a number of paths you can take.\n\n\n
## Move on to the next exercise\n\nThere are many more exercises you can practice with.  Grab the next one!\n\
n```\n$ exercism fetch java\n```\n\n\n## Review (and comment on) others' submissions to this exercise\n\nThe h
eart of Exercism are the conversations about coding\npractices.  It's definitely fun to practice, but engaging
 with others\nboth in their attempts and your own is how you get feedback.  That feedback\ncan help point out
what you're doing well and where you might need to\nimprove.\n\nSome submissions will be nearly identical to y
ours; others will be\ncompletely different.  Seeing both kinds can be instructive and interesting.\n\nNote tha
t you can only view submissions of others for exercises you have\ncompleted yourself.  This enriches the exper
ience of reading others' code\nbecause you'll have your own experience of trying to solve the problem.\n\nHere
's an up-to-date list of submissions on the Java track:\n\nhttp://exercism.io/tracks/java/exercises\n\n\n\n##
Submit another iteration\n\nYou are also encouraged to consider additional \"requirements\" on a given\nexerci
se.\n\nFor example, you could add a test or two that requires that the greeting\nuse the capitalized form on t
he person's name, regardless of the case they\nused.\n\nIn that situation, you'd write a test to set-up that n
ew expectation and\nthen implement that in the code (the same process we just went through\ntogether, above).\
n\n\n\n## Contribute to Exercism\n\nThe entire of Exercism is Open Source and is the labor of love for over\n1
00 maintainers and many more contributors.\n\nA starting point to jumping in can be found here:\n\nhttps://git
hub.com/exercism/x-common/blob/master/CONTRIBUTING.md\n\n\n----\n\nRegardless of what you decide to do next, w
e sincerely hope you learn\nand enjoy being part of this community.  If at any time you need assistance\ndo no
t hesitate to ask for help:\n\nhttp://exercism.io/languages/java/help\n\nCheers!\n","build.gradle":"apply plug
in: \"java\"\napply plugin: \"eclipse\"\napply plugin: \"idea\"\n\nrepositories {\n  mavenCentral()\n}\n\ndepe
ndencies {\n  testCompile \"junit:junit:4.12\"\n}\n\ntest {\n  testLogging {\n    exceptionFormat = 'full'\n
  events = [\"passed\", \"failed\", \"skipped\"]\n  }\n}\n","src/main/java/HelloWorld.java":"public class Hell
oWorld {\n    public static String hello(String name) {\n        throw new UnsupportedOperationException(\"Del
ete this statement and write your own implementation.\");\n    }\n}\n","src/test/java/HelloWorldTest.java":"im
port org.junit.Test;\nimport org.junit.Ignore;\n\nimport static org.junit.Assert.assertEquals;\n\npublic class
 HelloWorldTest {\n\n\n    @Test\n    public void helloNoName() {\n        assertEquals(\"Hello, World!\", Hel
loWorld.hello(\"\"));\n        assertEquals(\"Hello, World!\", HelloWorld.hello(null));\n    }\n\n    @Test\n
   @Ignore\n    public void emptyStringIsComparedByValue() {\n        assertEquals(\"Hello, World!\", HelloWor
ld.hello(new String(\"\")));\n    }\n    \n    @Test\n    @Ignore\n    public void helloSampleName() {\n
  assertEquals(\"Hello, Alice!\", HelloWorld.hello(\"Alice\"));\n    }\n\n    @Test\n    @Ignore\n    public v
oid helloAnotherSampleName() {\n        assertEquals(\"Hello, Bob!\", HelloWorld.hello(\"Bob\"));\n    }\n}\n"
,"README.md":"# Hello World\n\nThe classical introductory exercise. Just say \"Hello, World!\"\n\n[\"Hello, Wo
rld!\"](http://en.wikipedia.org/wiki/%22Hello,_world!%22_program) is\nthe traditional first program for beginn
ing programming in a new language\nor environment.\n\nThe objectives are simple:\n\n- Write a function that re
turns the string \"Hello, World!\".\n- Run the test suite and make sure that it succeeds.\n- Submit your solut
ion and check it at the website.\n\nIf everything goes well, you will be ready to fetch your first real exerci
se.\n\n\nTo run the tests:\n\n```sh\n$ gradle test\n```\n\nFor more detailed info about the Java track see the
 [help page](http://exercism.io/languages/java).\n\n## Source\n\nThis is an exercise to introduce users to usi
ng Exercism [http://en.wikipedia.org/wiki/%22Hello,_world!%22_program](http://en.wikipedia.org/wiki/%22Hello,_
world!%22_program)\n\n## Submitting Incomplete Problems\nIt's possible to submit an incomplete solution so you
 can see how others have completed the exercise.\n\n"},"fresh":false}]}

Request GET http://exercism.io/api/v1/exercises?key=8675cfd04f6e424aab2429418b0bd5bd
Response StatusCode=403
Response Body
?<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>

<title>Сообщение об ошибке</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />

<style>
body {

        background:#e5eaf5 url(/Wbo-92927394-94B7-4DC6-A5E0-95B476E172AB/bg.gif) top left repeat-x ;
        margin:0px 0px 0px 0px;
        font-family:Arial, Helvetica, sans-serif;
        min-width:1000px

2017/05/18 13:24:15 error parsing API response - invalid character 'i' looking for beginning of value
```

**Comment by kytrinyx** [comment]
> Katrina could you explain please term "fenceposts".

You've used them :) It's the three backticks that you put above and below the output.

I've edited your comment to redact the API key.


> Request GET http://exercism.io/api/v1/exercises?key=REDACTED
> Response StatusCode=403

This is the problem, but I can't see a reason why you would get a 403 Forbidden.

Would you please go to http://exercism.io/api/v1/exercises?key=YOUR_KEY_HERE in your browser and see what the page says?

**Comment by Wuppert** [comment]
Request
```
http://exercism.io/api/v1/exercises?key=8675cfd04f6e424aab2429418b0bd5bd
                               API Key: 8675cfd04f6e424aab2429418b0bd5bd

```
Response
```
{}
```

**Comment by Insti** [comment]
You seem determined to share your API key.

Are you going through a proxy of some kind?
That second 403 response does not look like something that exercism.io would be serving.

```
Request GET http://exercism.io/api/v1/exercises?key=REDACTED
Response StatusCode=403
Response Body
?<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>

<title>Сообщение об ошибке</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
```

[Google translate](https://translate.google.com/#ru/en/%D0%A1%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BE%D0%B1%20%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B5 ) suggests that `Сообщение об ошибке` means `Error message` in Russian.

**Comment by Wuppert** [comment]
Yes I share my key, Later I going to reset it
You are right, I going trough thу proxy
But I hadnt any difficulties with 
```
exercism upgrade
```
or client installation.That the reason to think ConnLineClient may see system properties for proxy server. Isnt it?

**Comment by kytrinyx** [comment]
`exercism upgrade` goes to github.com. I wonder if there's any way that the proxy server could have trouble with `exercism.io` but not `github.com`.

**Comment by kytrinyx** [comment]
@Wuppert Does this help?

https://github.com/exercism/exercism.io/blob/master/x/docs/md/help/firewall.md

**Comment by Wuppert** [comment]
@kytrinyx 
Thanks, Katrina. 
That is really what I need.
(on Windows should launch exercism fetch in PowerShall only.)

**Comment by kytrinyx** [comment]
@Wuppert do you have a suggestion for how our documentation could have helped you better?

**Comment by Wuppert** [comment]
@kytrinyx
It would be boldly
I guess should to investigate realization of your study process..and then..may be

**Comment by kytrinyx** [comment]
OK, if you ever have suggestions, please don't hesitate.

Closing, as it got sorted. Thanks!
