### ISSUE TITLE
Gradle errors on compile fresh hello world Java

### ISSUE THREAD

**Issue by zbranca** [exercism/exercism.io#3659]
Hello!

On a fresh fetch-ed Hello World, i do not receive expected test error, but an Gradle Exception.
I work on last 17.10 Ubuntu, 64bit.

Gradle 3.2.1
------------------------------------------------------------
Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.8
Ant:          Apache Ant(TM) version 1.9.9 compiled on June 29 2017
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.13.0-16-generic amd64

:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some child operations have not yet completed.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalStateException: Some child operations have not yet completed.
	at org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry$DefaultOperation.operationFinish(DefaultBuildOperationWorkerRegistry.java:183)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:197)
	at org.gradle.internal.Factories$1.create(Factories.java:25)

I reinstalled Gradle, delete and re-fetch sources, delete .gradle user forder, with same outcome.

**Comment by kytrinyx** [comment]
If this is about the Java track, would you go ahead and open an issue in http://github.com/exercism/java?

(If it's kotlin, then https://github.com/exercism/kotlin would be the right place).

That should get this in front of the people who are best placed to help you. Thank you ❤️
