### ISSUE TITLE
Runtime Error Error on Fedora 28

### ISSUE THREAD

**Issue by justyntemme** [exercism/exercism.io#3787]
Error when running any command on fedora 28 installing from repository package

```
panic: reflect: Call using *cli.Context as type *cli.Context [recovered]
	panic: reflect: Call using *cli.Context as type *cli.Context

goroutine 1 [running]:
github.com/urfave/cli.HandleAction.func1(0xc420077780)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:478 +0x23b
panic(0x76fe40, 0xc4200691e0)
	/usr/lib/golang/src/runtime/panic.go:505 +0x229
reflect.Value.call(0x77e180, 0x81e518, 0x13, 0x7fe8c9, 0x4, 0xc420077740, 0x1, 0x1, 0xc4200320c0, 0x7f2d60, ...)
	/usr/lib/golang/src/reflect/value.go:377 +0x1202
reflect.Value.Call(0x77e180, 0x81e518, 0x13, 0xc420077740, 0x1, 0x1, 0x7283d6, 0x7febc9, 0x4)
	/usr/lib/golang/src/reflect/value.go:308 +0xa4
github.com/urfave/cli.HandleAction(0x77e180, 0x81e518, 0xc4200ea500, 0x0, 0x0)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:487 +0x16d
github.com/urfave/cli.Command.Run(0x7fed09, 0x4, 0x7fe4ff, 0x2, 0x0, 0x0, 0x0, 0x817d92, 0x61, 0x0, ...)
	/usr/share/gocode/src/github.com/urfave/cli/command.go:189 +0x9a9
github.com/urfave/cli.(*App).Run(0xc420001800, 0xc42000c060, 0x2, 0x2, 0x0, 0x0)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:240 +0x546
main.main()
	/builddir/build/BUILD/cli-2.4.1/exercism/main.go:188 +0xcbf
```

**Comment by kytrinyx** [comment]
What's the output of `exercism debug`?

**Comment by NobbZ** [comment]
@justyntemme how have you installed the CLI?

* Did you use a package for your system? If so, which?
* Did you use the tarballs from the github release page? If so, which?
* Did you do a installation from source? If so, which version of go did you use?

**Comment by NobbZ** [comment]
@kytrinyx as he said "running any command", I fear, its the same.

Especially as the framework is affected by the message that actually dispatches the sub commands…

**Comment by justyntemme** [comment]
exercism debug output
```
panic: reflect: Call using *cli.Context as type *cli.Context [recovered]
	panic: reflect: Call using *cli.Context as type *cli.Context

goroutine 1 [running]:
github.com/urfave/cli.HandleAction.func1(0xc420077780)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:478 +0x23b
panic(0x76fe40, 0xc4200a71e0)
	/usr/lib/golang/src/runtime/panic.go:505 +0x229
reflect.Value.call(0x77e180, 0x81e4f8, 0x13, 0x7fe8c9, 0x4, 0xc420077740, 0x1, 0x1, 0xc4200b6040, 0x7f2d60, ...)
	/usr/lib/golang/src/reflect/value.go:377 +0x1202
reflect.Value.Call(0x77e180, 0x81e4f8, 0x13, 0xc420077740, 0x1, 0x1, 0x7283d6, 0x7febc9, 0x4)
	/usr/lib/golang/src/reflect/value.go:308 +0xa4
github.com/urfave/cli.HandleAction(0x77e180, 0x81e4f8, 0xc4200fe500, 0x0, 0x0)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:487 +0x16d
github.com/urfave/cli.Command.Run(0x7ff3ef, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80e6dd, 0x21, 0x0, ...)
	/usr/share/gocode/src/github.com/urfave/cli/command.go:189 +0x9a9
github.com/urfave/cli.(*App).Run(0xc420090780, 0xc4200b8000, 0x2, 0x2, 0x0, 0x0)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:240 +0x546
main.main()
```

Being a docker nerd I got it up and runnign in docker no problem. I may open a pr with a script to automate all docker setup as the simple `docker-compose up` will not wrk

It seems like an issue with a go package. 

I installed from the system package currently default on fedora 28, not source
```
output of `exercism version` >> panic: reflect: Call using *cli.Context as type *cli.Context [recovered]
	panic: reflect: Call using *cli.Context as type *cli.Context

goroutine 1 [running]:
github.com/urfave/cli.HandleAction.func1(0xc420077780)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:478 +0x23b
panic(0x76fe40, 0xc4200a71e0)
	/usr/lib/golang/src/runtime/panic.go:505 +0x229
reflect.Value.call(0x77e180, 0x81e4f8, 0x13, 0x7fe8c9, 0x4, 0xc420077740, 0x1, 0x1, 0xc4200b6040, 0x7f2d60, ...)
	/usr/lib/golang/src/reflect/value.go:377 +0x1202
reflect.Value.Call(0x77e180, 0x81e4f8, 0x13, 0xc420077740, 0x1, 0x1, 0x7283d6, 0x7febc9, 0x4)
	/usr/lib/golang/src/reflect/value.go:308 +0xa4
github.com/urfave/cli.HandleAction(0x77e180, 0x81e4f8, 0xc4200fe500, 0x0, 0x0)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:487 +0x16d
github.com/urfave/cli.Command.Run(0x7ff3ef, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80e6dd, 0x21, 0x0, ...)
	/usr/share/gocode/src/github.com/urfave/cli/command.go:189 +0x9a9
github.com/urfave/cli.(*App).Run(0xc420090780, 0xc4200b8000, 0x2, 0x2, 0x0, 0x0)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:240 +0x546
main.main()
```

Awesome job on the prompt reply, I am a go developer, so if there is anything else you need , perhaps an strace or something please let me know. thanks guys! here is to a go developer learning php :/

**Comment by NobbZ** [comment]
I'm not comfortable with the procedures around fedora packaging, but if you really installed `exercism` from an official repository, you should report this as a packaging bug.

Probably you should convince them to simply use the provided pre-built binary and simply repackage it.

That will cause much less problems.

**Comment by justyntemme** [comment]
Fixed in latest update to a dependency package
