### ISSUE TITLE
Mentorcism submit panic

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3931]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/152._
_Originally posted by @JoelQ._

#

Looks like there are some hard-coded paths in here? I tried to submit an exercise (after moving the binary 😬 ) an things blew up. I was able to fix the issue by re-configuring things correctly and running a bare `mentorcism submit` in the desired directory.

```
% mentorcism submit hello-world                                    
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13a1174]

goroutine 1 [running]:
github.com/exercism/cli/workspace.Workspace.Locate.func1(0xc4200de210, 0x23, 0x0, 0x0, 0x150e880, 0xc4201b28d0, 0x0, 0x0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/workspace/workspace.go:65 +0x44
path/filepath.Walk(0xc4200de210, 0x23, 0xc42012eb40, 0x0, 0x150e880)
        /usr/local/Cellar/go/1.10.3/libexec/src/path/filepath/path.go:401 +0x6c
github.com/exercism/cli/workspace.Workspace.Locate(0xc4200de210, 0x23, 0x7fff5fbff8aa, 0xb, 0x1, 0xc4200b6640, 0x0, 0x0, 0xc4200c8609)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/workspace/workspace.go:100 +0x18c
github.com/exercism/cli/cmd.glob..func6(0x17d8340, 0xc4200ab3f0, 0x1, 0x1, 0x0, 0x0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/cmd/submit.go:73 +0x168
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).execute(0x17d8340, 0xc4200ab3b0, 0x1, 0x1, 0x17d8340, 0xc4200ab3b0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:649 +0x449
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x17d7a40, 0x100620c, 0xc42009a058, 0x0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:728 +0x2d4
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x17d7a40, 0x0, 0xc4200b47a0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:687 +0x2b
github.com/exercism/cli/cmd.Execute()
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/cmd/root.go:45 +0x2d
main.main()
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/exercism/main.go:6 +0x20
```

**Comment by iHiD** [comment]
This is being tracked in another issue.
