### ISSUE TITLE
ActiveStorage blew up somehow

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism.io#4057]
@kntsoriano See the exception at the bottom of this. I'm rescuing it now, but can you try and work out what happened pls? I've asked @dmagro not to update his profile photo for now so we can try to debug it. Thanks.

```
2.3.0 :001 > User.find_by_handle("dmagro")
   (0.9ms)  SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci,  @@SESSION.sql_mode = 'traditional',  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
  User Load (1.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`handle` = 'dmagro' LIMIT 1
  ActiveStorage::Attachment Load (0.7ms)  SELECT  `active_storage_attachments`.* FROM `active_storage_attachments` WHERE `active_storage_attachments`.`record_id` = 173070 AND `active_storage_attachments`.`record_type` = 'User' AND `active_storage_attachments`.`name` = 'avatar' LIMIT 1
  ActiveStorage::Blob Load (0.8ms)  SELECT  `active_storage_blobs`.* FROM `active_storage_blobs` WHERE `active_storage_blobs`.`id` = 47 LIMIT 1
ActiveStorage::InvariableError: ActiveStorage::InvariableError
	from app/models/user.rb:144:in `avatar_thumbnail_url'
	from app/models/user.rb:79:in `avatar_url'
```

**Comment by tejasbubane** [comment]
This error is coming from [here](https://github.com/rails/rails/blob/master/activestorage/app/models/active_storage/blob/representable.rb#L28-L34) inside ActiveStorage. I guess this means the file cannot be processed by `ImageMagick`.

These are the allowed file variants: https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/engine.rb#L24-L31
